#!/bin/sh

HOOKS="post-commit post-merge post-checkout"

cd ~/

git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

git clone https://github.com/universal-ctags/ctags.git ~/ctags

cd ~/ctags
./autogen.sh
./configure --prefix=/usr/local/
make

yes | sudo ~/configs/su_script

cd ~/
cp ~/configs/vimWPlug ~/.vimrc
cp ~/configs/tmuxconfig ~/.tmux.conf

git config --global init.templatedir '~/.git_template'
mkdir -p ~/.git_template/hooks
cp ~/configs/ctags_git ~/.git_template/hooks/

cd ~/.git_template/hooks/

for name in $HOOKS; do
	touch $name
	chmod a+x $name
	echo 
"#!/bin/sh
.git/hooks/ctags >/dev/null 2>&1 &" >> $name
done
