#!/bin/sh

sudo make install

apt update
apt upgrade

apt install \
	gcc make \
	pkg-config autoconf automake \
	python3-docutils \
	libseccomp-dev \
	libjansson-dev \
	libyaml-dev \
	libxml2-dev \
	tmux
